version: '3.8'
services:
  api:
    build: .
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db

  pg:
    image: postgres:16.3-alpine3.20
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
      - "POSTGRES_DB=${PG_DB}"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "${PG_PORT}:5432"

volumes:
  postgres_data: